on:
  push:
    branches:
      - main
    paths: &paths
      - .github/workflows/run-tests.yml
      - package.json
      - package-lock.json
      - server.js
      - src/**/*
      - tests/**/*
  pull_request:
    paths: *paths

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci && npx playwright install chromium firefox

      - name: Build the scripts
        run: npm run build

      - name: Start server and run tests
        run: npm start & sleep 5 && npm test:ci

      - name: Generate test report
        run: npx junit-viewer --results=public/tests/junit.xml --save=public/tests/report.html

      - name: Gather test reports
        uses: actions/upload-artifact@v7
        with:
          name: Test Reports
          path: |
            public/tests/junit.xml
            public/tests/report.html
