on:
  push:
    branches:
      - main
    paths: &paths
      - .github/workflows/run-build.yml
      - package.json
      - package-lock.json
      - src/**/*.ts
  pull_request:
    paths: *paths
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:22-alpine
      volumes:
        - .:/app
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run Build
        run: npm run build


